name: triggers
on: 
  workflow_dispatch: 
  #push  # triggers the workflow on the every push to the repository

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: manually dispatched
        run: echo "manually dispatched"


name: triggers
on:
  push:
    branches:
      - 'feature*'
  #workflow_dispatch: 
  #push  # triggers the workflow on the every push to the repository

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: feature branches push
        run: echo "feature branche push"
