name: context demo
on:
  push
env:
  project: "roboshop"
  environment: "dev"
  component: "catalogue"

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print info  
        run: |   
          echo '${{ toJson(github) }}'
          echo "branche name: ${{ github.ref_name }}"

      - name: access env variables
        run: |
          echo "project: $project"
          echo "environment: $environment"
          echo "component: $component"

      - name: Print secrets
        run: |
          echo "DB USER name: ${{ secrets.DB_USER }}"
          echo "DB PASSWORD ${{ secrets.DB_PASSWORD }}"
      
      - name: Print variables
        run: |
          echo "DB URL: ${{ vars.DB_URL}}"
      
      - name: image tags
        id: tag
        run: |
          echo "version=1.0.0 >>$GITHUB_OUTPUT"
          echo "image-name=catalogue >>GITHUB_OUTPUT"


      - name: Print previous step GITHUB_OUTPUT
        run: |
          echo "image tags ${{ steps.tag.outputs.image-name }}"
          echo "image tags ${{ steps.tag.outputs.version }}"
      


  