name: context demo
on:
  push
env:
  project: "roboshop"
  environment: "dev"
  component: "catalogue"

jobs:
  github-context:
    runs-on: ubuntu-latest

  outputs:
    image_name: ${{ steps.tag.outputs.image_name }}
    version: ${{ step.tag.outputs.version }}
    
    steps:
      - name: Print info  
        run: |   
          echo '${{ toJson(github) }}'
          echo "branche name: ${{ github.ref_name }}"

      - name: access env variables
        run: |
          echo "project: $project"
          echo "environment: $environment"
          echo "component: $component"

      - name: Print secrets
        run: |
          echo "DB USER name: ${{ secrets.DB_USER }}"
          echo "DB PASSWORD ${{ secrets.DB_PASSWORD }}"
      
      - name: Print variables
        run: |
          echo "DB URL: ${{ vars.DB_URL}}"
      
      - name: image tags
        id: tag
        run: |
          echo "version=1.0.0" >> $GITHUB_OUTPUT
          echo "image_name=catalogue" >> $GITHUB_OUTPUT


      - name: Print previous step outputs
        run: |
          echo "image name: ${{ steps.tag.outputs.image_name }}"
          echo "version: ${{ steps.tag.outputs.version }}"

      # use full with in the job 
      - name: Github env
        run: |
          echo "course=github-actions" >> $GITHUB_ENV
          echo "duration=10hourse" >> $GITHUB_ENV
      
      - name: Print github env outputs
        run: |
          echo "course: $course"
          echo "duration: $duration"
  
  deploy:
    runs-on: ubuntu-latest
    needs: github-context   # depends on the above job 
    steps:
      - name: Print github env in to another job 
        run: |
          echo "image_name: ${{ needs.github-context.outputs.image_name }}"
          echo "version: ${{ needs.github-context.outputs.version }}"


  